/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.leshka_and_friends.lgvb.view.matisse;

/**
 *
 * @author giann
 */
public class OptionItemPanel extends RoundedPanel {

    /**
     * Creates new form OptionItemPanel
     */
    public OptionItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuItemLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 1));
        setLayout(new java.awt.BorderLayout());

        menuItemLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuItemLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuItemLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Dashboard-14px.png"))); // NOI18N
        menuItemLabel.setText("label");
        menuItemLabel.setIconTextGap(10);
        add(menuItemLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel menuItemLabel;
    // End of variables declaration//GEN-END:variables
}
