/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.leshka_and_friends.lgvb.view.matisse;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author giann
 */
public class Sidebar extends javax.swing.JPanel {

    private MenuItemPanel[] menuItems;

    /**
     * Creates new form Sidebar
     */
    public Sidebar() {
        initComponents();
        initMenuBehavior();
        initOptionBehavior();

        SwingUtilities.invokeLater(this::initMenuIcons);
    }

    private void initMenuBehavior() {
        // put all menu panels in an array
        menuItems = new MenuItemPanel[]{
            dashboardItem, walletItem, loanReqItem, cardsItem
        };

        // first one selected by default
        setSelectedMenu(dashboardItem);

        // add click listeners
        for (MenuItemPanel item : menuItems) {
            item.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    setSelectedMenu(item);
                }
            });
        }
    }

    private void initMenuIcons() {
        dashboardItem.setItemIcon(new ImageIcon(getClass().getResource("/icons/dashboard.png")));
        walletItem.setItemIcon(new ImageIcon(getClass().getResource("/icons/wallet.png")));
        loanReqItem.setItemIcon(new ImageIcon(getClass().getResource("/icons/loanReq.png")));
        cardsItem.setItemIcon(new ImageIcon(getClass().getResource("/icons/card.png")));
    }

    private void setSelectedMenu(MenuItemPanel selectedItem) {
        for (MenuItemPanel item : menuItems) {
            item.setSelected(item == selectedItem);
        }
    }
    
    private void initOptionBehavior() {
        accountItem.setUseClickColor(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        middleContainer = new javax.swing.JPanel();
        menuItemContainer = new javax.swing.JPanel();
        dashboardItem = new com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel();
        walletItem = new com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel();
        loanReqItem = new com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel();
        cardsItem = new com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel();
        separatorPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        optionItemContainer = new javax.swing.JPanel();
        accountItem = new com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel();
        settingsItem = new com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel();
        southContainer = new javax.swing.JPanel();
        userProfileItem = new com.leshka_and_friends.lgvb.view.matisse.UserProfile();

        setBackground(new java.awt.Color(5, 5, 38));
        setMaximumSize(new java.awt.Dimension(238, 720));
        setPreferredSize(new java.awt.Dimension(238, 720));
        setLayout(new java.awt.BorderLayout());

        northContainer.setOpaque(false);
        northContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/logo-white-95px.png"))); // NOI18N
        northContainer.add(jLabel1);

        add(northContainer, java.awt.BorderLayout.PAGE_START);

        middleContainer.setMaximumSize(new java.awt.Dimension(238, 720));
        middleContainer.setMinimumSize(new java.awt.Dimension(238, 550));
        middleContainer.setOpaque(false);
        middleContainer.setPreferredSize(new java.awt.Dimension(238, 550));
        middleContainer.setLayout(new javax.swing.BoxLayout(middleContainer, javax.swing.BoxLayout.Y_AXIS));

        menuItemContainer.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1)));
        menuItemContainer.setMaximumSize(new java.awt.Dimension(238, 270));
        menuItemContainer.setMinimumSize(new java.awt.Dimension(238, 101));
        menuItemContainer.setOpaque(false);
        menuItemContainer.setPreferredSize(new java.awt.Dimension(238, 215));
        menuItemContainer.setLayout(new javax.swing.BoxLayout(menuItemContainer, javax.swing.BoxLayout.Y_AXIS));

        dashboardItem.setItemIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // NOI18N
        dashboardItem.setItemText("Dashboard");
        dashboardItem.setMaximumSize(new java.awt.Dimension(198, 36));
        dashboardItem.setPreferredSize(new java.awt.Dimension(198, 36));
        menuItemContainer.add(dashboardItem);

        walletItem.setItemIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wallet.png"))); // NOI18N
        walletItem.setItemText("Wallet");
        walletItem.setMaximumSize(new java.awt.Dimension(198, 36));
        walletItem.setPreferredSize(new java.awt.Dimension(198, 36));
        menuItemContainer.add(walletItem);

        loanReqItem.setItemIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loanReq.png"))); // NOI18N
        loanReqItem.setItemText("Loan Requests");
        loanReqItem.setMaximumSize(new java.awt.Dimension(198, 36));
        loanReqItem.setPreferredSize(new java.awt.Dimension(198, 36));
        menuItemContainer.add(loanReqItem);

        cardsItem.setItemIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/card.png"))); // NOI18N
        cardsItem.setItemText("Cards");
        cardsItem.setMaximumSize(new java.awt.Dimension(198, 36));
        cardsItem.setPreferredSize(new java.awt.Dimension(198, 36));
        menuItemContainer.add(cardsItem);

        middleContainer.add(menuItemContainer);

        separatorPanel.setMaximumSize(new java.awt.Dimension(238, 50));
        separatorPanel.setOpaque(false);
        separatorPanel.setPreferredSize(new java.awt.Dimension(238, 10));
        separatorPanel.setLayout(new java.awt.BorderLayout());

        jSeparator1.setEnabled(false);
        jSeparator1.setRequestFocusEnabled(false);
        separatorPanel.add(jSeparator1, java.awt.BorderLayout.CENTER);

        middleContainer.add(separatorPanel);

        optionItemContainer.setMaximumSize(new java.awt.Dimension(238, 270));
        optionItemContainer.setMinimumSize(new java.awt.Dimension(238, 214));
        optionItemContainer.setOpaque(false);
        optionItemContainer.setPreferredSize(new java.awt.Dimension(238, 210));
        optionItemContainer.setLayout(new javax.swing.BoxLayout(optionItemContainer, javax.swing.BoxLayout.Y_AXIS));

        accountItem.setItemIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        accountItem.setItemText("Account");
        accountItem.setUseClickColor(false);
        accountItem.setMaximumSize(new java.awt.Dimension(198, 36));
        accountItem.setMinimumSize(new java.awt.Dimension(198, 36));
        accountItem.setPreferredSize(new java.awt.Dimension(198, 36));
        optionItemContainer.add(accountItem);

        settingsItem.setItemIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.png"))); // NOI18N
        settingsItem.setItemText("Settings");
        settingsItem.setUseClickColor(false);
        settingsItem.setMaximumSize(new java.awt.Dimension(198, 36));
        settingsItem.setMinimumSize(new java.awt.Dimension(198, 36));
        settingsItem.setPreferredSize(new java.awt.Dimension(198, 36));
        optionItemContainer.add(settingsItem);

        middleContainer.add(optionItemContainer);

        add(middleContainer, java.awt.BorderLayout.CENTER);

        southContainer.setBackground(new java.awt.Color(204, 255, 255));
        southContainer.setForeground(new java.awt.Color(153, 153, 153));
        southContainer.setOpaque(false);
        southContainer.setPreferredSize(new java.awt.Dimension(238, 80));
        southContainer.setLayout(new javax.swing.BoxLayout(southContainer, javax.swing.BoxLayout.Y_AXIS));
        southContainer.add(userProfileItem);

        add(southContainer, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel accountItem;
    private com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel cardsItem;
    private com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel dashboardItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel loanReqItem;
    private javax.swing.JPanel menuItemContainer;
    private javax.swing.JPanel middleContainer;
    private javax.swing.JPanel northContainer;
    private javax.swing.JPanel optionItemContainer;
    private javax.swing.JPanel separatorPanel;
    private com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel settingsItem;
    private javax.swing.JPanel southContainer;
    private com.leshka_and_friends.lgvb.view.matisse.UserProfile userProfileItem;
    private com.leshka_and_friends.lgvb.view.matisse.MenuItemPanel walletItem;
    // End of variables declaration//GEN-END:variables
}
