/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.leshka_and_friends.lgvb.view.matisse;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.Box;
import javax.swing.ImageIcon;

/**
 *
 * @author giann
 */
public class UserProfile extends RoundedPanel {

    /**
     * Creates new form UserProfile
     */
    private AvatarPanel avatarPanel;

    public UserProfile() {
        initComponents();
        
        setOpaque(false);

        // Replace placeholder avatar with AvatarPanel
        avatarPanel = new AvatarPanel(null, 34); // size matches original layout
        int avatarIndex = 0; // index in BoxLayout
        remove(avatar);
        add(avatarPanel, avatarIndex);

        // Add spacing between avatar and label
        add(Box.createRigidArea(new Dimension(15, 0)), 1);

        // Example profile
        setUserProfile("Gianne Pesana", "/profile/pesana.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatar = new javax.swing.JPanel();
        profileName = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        setForeground(new java.awt.Color(60, 63, 65));
        setMaximumSize(new java.awt.Dimension(198, 36));
        setMinimumSize(new java.awt.Dimension(198, 36));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(198, 36));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        avatar.setMaximumSize(new java.awt.Dimension(34, 34));
        avatar.setMinimumSize(new java.awt.Dimension(34, 34));
        avatar.setPreferredSize(new java.awt.Dimension(34, 34));

        javax.swing.GroupLayout avatarLayout = new javax.swing.GroupLayout(avatar);
        avatar.setLayout(avatarLayout);
        avatarLayout.setHorizontalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        avatarLayout.setVerticalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        add(avatar);

        profileName.setForeground(new java.awt.Color(255, 255, 255));
        profileName.setText("placeholder");
        add(profileName);
    }// </editor-fold>//GEN-END:initComponents

    public void setUserProfile(String name, String resourcePath) {
        profileName.setText(name);

        java.net.URL imgUrl = getClass().getResource(resourcePath);
        if (imgUrl != null) {
            ImageIcon icon = new ImageIcon(imgUrl);
            BufferedImage img = new BufferedImage(
                    icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB
            );
            Graphics2D g2d = img.createGraphics();
            icon.paintIcon(null, g2d, 0, 0);
            g2d.dispose();

            avatarPanel.setImage(img);
        } else {
            System.err.println("Image not found: " + resourcePath);
        }
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel avatar;
    private javax.swing.JLabel profileName;
    // End of variables declaration//GEN-END:variables
}
