/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.leshka_and_friends.lgvb.view.test;

/**
 *
 * @author giann
 */
public class CardPanel extends javax.swing.JPanel {

    /**
     * Creates new form CardPanel
     */
    public CardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new com.leshka_and_friends.lgvbtest.matisse.RoundedPanel();
        header = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        headerEastContainer = new javax.swing.JPanel();
        cardType = new javax.swing.JLabel();
        visaIcon = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cardNumberContainer = new javax.swing.JPanel();
        cardNumberLabel = new javax.swing.JLabel();
        cardDetails = new javax.swing.JPanel();
        expiryContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        expiryDate = new javax.swing.JLabel();
        cardHolderContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nameContainer = new javax.swing.JPanel();
        cardHolderName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        roundedPanel1.setBackground(new java.awt.Color(17, 17, 51));
        roundedPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 30));
        roundedPanel1.setLayout(new javax.swing.BoxLayout(roundedPanel1, javax.swing.BoxLayout.Y_AXIS));

        header.setBackground(new java.awt.Color(153, 153, 153));
        header.setMaximumSize(new java.awt.Dimension(32767, 57));
        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(100, 57));
        header.setLayout(new java.awt.BorderLayout());

        logoIcon.setText("logoIcon");
        logoIcon.setMaximumSize(new java.awt.Dimension(76, 29));
        logoIcon.setMinimumSize(new java.awt.Dimension(76, 29));
        logoIcon.setPreferredSize(new java.awt.Dimension(76, 29));
        header.add(logoIcon, java.awt.BorderLayout.LINE_START);

        headerEastContainer.setMaximumSize(new java.awt.Dimension(126, 32767));
        headerEastContainer.setOpaque(false);
        headerEastContainer.setPreferredSize(new java.awt.Dimension(126, 100));
        headerEastContainer.setLayout(new java.awt.GridLayout(1, 2));

        cardType.setFont(new java.awt.Font("IBM Plex Mono SemiBold", 1, 14)); // NOI18N
        cardType.setText("DEBIT");
        headerEastContainer.add(cardType);

        visaIcon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        visaIcon.setText("visaIcon");
        headerEastContainer.add(visaIcon);

        header.add(headerEastContainer, java.awt.BorderLayout.LINE_END);

        roundedPanel1.add(header);

        container.setMaximumSize(new java.awt.Dimension(32767, 65));
        container.setOpaque(false);
        container.setPreferredSize(new java.awt.Dimension(100, 65));
        container.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 25));

        jLabel1.setText("icon");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 32));
        container.add(jLabel1);

        roundedPanel1.add(container);

        cardNumberContainer.setMaximumSize(new java.awt.Dimension(32767, 40));
        cardNumberContainer.setOpaque(false);
        cardNumberContainer.setPreferredSize(new java.awt.Dimension(100, 40));
        cardNumberContainer.setLayout(new java.awt.BorderLayout());

        cardNumberLabel.setFont(new java.awt.Font("IBM Plex Mono SemiBold", 0, 20)); // NOI18N
        cardNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardNumberLabel.setText("4319   5312   0215   1289");
        cardNumberContainer.add(cardNumberLabel, java.awt.BorderLayout.CENTER);

        roundedPanel1.add(cardNumberContainer);

        cardDetails.setOpaque(false);
        cardDetails.setLayout(new java.awt.BorderLayout());

        expiryContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        expiryContainer.setMaximumSize(new java.awt.Dimension(85, 32767));
        expiryContainer.setOpaque(false);
        expiryContainer.setPreferredSize(new java.awt.Dimension(85, 100));
        expiryContainer.setLayout(new javax.swing.BoxLayout(expiryContainer, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("IBM Plex Mono", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("EXPIRES");
        jLabel2.setMaximumSize(new java.awt.Dimension(85, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(85, 20));
        expiryContainer.add(jLabel2);

        expiryDate.setFont(new java.awt.Font("IBM Plex Mono Medium", 0, 14)); // NOI18N
        expiryDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        expiryDate.setText("10/27");
        expiryDate.setMaximumSize(new java.awt.Dimension(85, 19));
        expiryDate.setPreferredSize(new java.awt.Dimension(85, 19));
        expiryContainer.add(expiryDate);

        cardDetails.add(expiryContainer, java.awt.BorderLayout.LINE_END);

        cardHolderContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        cardHolderContainer.setOpaque(false);
        cardHolderContainer.setLayout(new javax.swing.BoxLayout(cardHolderContainer, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("IBM Plex Mono", 0, 12)); // NOI18N
        jLabel4.setText("CARD HOLDER");
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        cardHolderContainer.add(jPanel1);

        nameContainer.setOpaque(false);
        nameContainer.setLayout(new java.awt.BorderLayout());

        cardHolderName.setFont(new java.awt.Font("IBM Plex Mono Medium", 0, 14)); // NOI18N
        cardHolderName.setText("Leshka Alcontin");
        nameContainer.add(cardHolderName, java.awt.BorderLayout.CENTER);

        cardHolderContainer.add(nameContainer);

        cardDetails.add(cardHolderContainer, java.awt.BorderLayout.CENTER);

        roundedPanel1.add(cardDetails);

        add(roundedPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardDetails;
    private javax.swing.JPanel cardHolderContainer;
    private javax.swing.JLabel cardHolderName;
    private javax.swing.JPanel cardNumberContainer;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JLabel cardType;
    private javax.swing.JPanel container;
    private javax.swing.JPanel expiryContainer;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JPanel header;
    private javax.swing.JPanel headerEastContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JPanel nameContainer;
    private com.leshka_and_friends.lgvbtest.matisse.RoundedPanel roundedPanel1;
    private javax.swing.JLabel visaIcon;
    // End of variables declaration//GEN-END:variables
}
