/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.leshka_and_friends.lgvb.view.test;

/**
 *
 * @author giann
 */
public class DHB extends javax.swing.JPanel {

    /**
     * Creates new form DHB
     */
    public DHB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topContainer = new javax.swing.JPanel();
        notificationPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        setMaximumSize(new java.awt.Dimension(1042, 720));
        setPreferredSize(new java.awt.Dimension(1042, 720));
        setLayout(new java.awt.BorderLayout());

        topContainer.setBackground(new java.awt.Color(102, 102, 102));
        topContainer.setOpaque(false);
        topContainer.setPreferredSize(new java.awt.Dimension(1042, 107));
        topContainer.setLayout(new java.awt.BorderLayout());

        notificationPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout notificationPanelLayout = new javax.swing.GroupLayout(notificationPanel);
        notificationPanel.setLayout(notificationPanelLayout);
        notificationPanelLayout.setHorizontalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        notificationPanelLayout.setVerticalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        topContainer.add(notificationPanel, java.awt.BorderLayout.LINE_END);

        headerPanel.setBackground(new java.awt.Color(102, 102, 102));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 1, 1));
        headerPanel.setLayout(new javax.swing.BoxLayout(headerPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        jLabel1.setText("Hi, Leshka");
        jLabel1.setMaximumSize(new java.awt.Dimension(164, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(164, 48));
        headerPanel.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Baloo 2 SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Today, <date>");
        headerPanel.add(jLabel2);

        topContainer.add(headerPanel, java.awt.BorderLayout.CENTER);

        add(topContainer, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel notificationPanel;
    private javax.swing.JPanel topContainer;
    // End of variables declaration//GEN-END:variables
}
